/**
 * Country calling codes for telephone number input
 * South Africa (+27) is listed first as the default option
 */

export interface CountryCode {
  code: string;
  country: string;
  dialCode: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  { code: "ZA", country: "South Africa", dialCode: "+27" },
  { code: "AF", country: "Afghanistan", dialCode: "+93" },
  { code: "AL", country: "Albania", dialCode: "+355" },
  { code: "DZ", country: "Algeria", dialCode: "+213" },
  { code: "AD", country: "Andorra", dialCode: "+376" },
  { code: "AO", country: "Angola", dialCode: "+244" },
  { code: "AR", country: "Argentina", dialCode: "+54" },
  { code: "AM", country: "Armenia", dialCode: "+374" },
  { code: "AU", country: "Australia", dialCode: "+61" },
  { code: "AT", country: "Austria", dialCode: "+43" },
  { code: "AZ", country: "Azerbaijan", dialCode: "+994" },
  { code: "BH", country: "Bahrain", dialCode: "+973" },
  { code: "BD", country: "Bangladesh", dialCode: "+880" },
  { code: "BY", country: "Belarus", dialCode: "+375" },
  { code: "BE", country: "Belgium", dialCode: "+32" },
  { code: "BZ", country: "Belize", dialCode: "+501" },
  { code: "BJ", country: "Benin", dialCode: "+229" },
  { code: "BT", country: "Bhutan", dialCode: "+975" },
  { code: "BO", country: "Bolivia", dialCode: "+591" },
  { code: "BA", country: "Bosnia and Herzegovina", dialCode: "+387" },
  { code: "BW", country: "Botswana", dialCode: "+267" },
  { code: "BR", country: "Brazil", dialCode: "+55" },
  { code: "BN", country: "Brunei", dialCode: "+673" },
  { code: "BG", country: "Bulgaria", dialCode: "+359" },
  { code: "BF", country: "Burkina Faso", dialCode: "+226" },
  { code: "BI", country: "Burundi", dialCode: "+257" },
  { code: "KH", country: "Cambodia", dialCode: "+855" },
  { code: "CM", country: "Cameroon", dialCode: "+237" },
  { code: "CA", country: "Canada", dialCode: "+1" },
  { code: "CV", country: "Cabo Verde", dialCode: "+238" },
  { code: "CF", country: "Central African Republic", dialCode: "+236" },
  { code: "TD", country: "Chad", dialCode: "+235" },
  { code: "CL", country: "Chile", dialCode: "+56" },
  { code: "CN", country: "China", dialCode: "+86" },
  { code: "CO", country: "Colombia", dialCode: "+57" },
  { code: "KM", country: "Comoros", dialCode: "+269" },
  { code: "CG", country: "Congo", dialCode: "+242" },
  { code: "CD", country: "Congo (DRC)", dialCode: "+243" },
  { code: "CR", country: "Costa Rica", dialCode: "+506" },
  { code: "HR", country: "Croatia", dialCode: "+385" },
  { code: "CU", country: "Cuba", dialCode: "+53" },
  { code: "CY", country: "Cyprus", dialCode: "+357" },
  { code: "CZ", country: "Czech Republic", dialCode: "+420" },
  { code: "DK", country: "Denmark", dialCode: "+45" },
  { code: "DJ", country: "Djibouti", dialCode: "+253" },
  { code: "DO", country: "Dominican Republic", dialCode: "+1-809" },
  { code: "EC", country: "Ecuador", dialCode: "+593" },
  { code: "EG", country: "Egypt", dialCode: "+20" },
  { code: "SV", country: "El Salvador", dialCode: "+503" },
  { code: "GQ", country: "Equatorial Guinea", dialCode: "+240" },
  { code: "ER", country: "Eritrea", dialCode: "+291" },
  { code: "EE", country: "Estonia", dialCode: "+372" },
  { code: "SZ", country: "Eswatini", dialCode: "+268" },
  { code: "ET", country: "Ethiopia", dialCode: "+251" },
  { code: "FJ", country: "Fiji", dialCode: "+679" },
  { code: "FI", country: "Finland", dialCode: "+358" },
  { code: "FR", country: "France", dialCode: "+33" },
  { code: "GA", country: "Gabon", dialCode: "+241" },
  { code: "GM", country: "Gambia", dialCode: "+220" },
  { code: "GE", country: "Georgia", dialCode: "+995" },
  { code: "DE", country: "Germany", dialCode: "+49" },
  { code: "GH", country: "Ghana", dialCode: "+233" },
  { code: "GR", country: "Greece", dialCode: "+30" },
  { code: "GT", country: "Guatemala", dialCode: "+502" },
  { code: "GN", country: "Guinea", dialCode: "+224" },
  { code: "GW", country: "Guinea-Bissau", dialCode: "+245" },
  { code: "GY", country: "Guyana", dialCode: "+592" },
  { code: "HT", country: "Haiti", dialCode: "+509" },
  { code: "HN", country: "Honduras", dialCode: "+504" },
  { code: "HU", country: "Hungary", dialCode: "+36" },
  { code: "IS", country: "Iceland", dialCode: "+354" },
  { code: "IN", country: "India", dialCode: "+91" },
  { code: "ID", country: "Indonesia", dialCode: "+62" },
  { code: "IR", country: "Iran", dialCode: "+98" },
  { code: "IQ", country: "Iraq", dialCode: "+964" },
  { code: "IE", country: "Ireland", dialCode: "+353" },
  { code: "IL", country: "Israel", dialCode: "+972" },
  { code: "IT", country: "Italy", dialCode: "+39" },
  { code: "CI", country: "Ivory Coast", dialCode: "+225" },
  { code: "JM", country: "Jamaica", dialCode: "+1-876" },
  { code: "JP", country: "Japan", dialCode: "+81" },
  { code: "JO", country: "Jordan", dialCode: "+962" },
  { code: "KZ", country: "Kazakhstan", dialCode: "+7" },
  { code: "KE", country: "Kenya", dialCode: "+254" },
  { code: "KW", country: "Kuwait", dialCode: "+965" },
  { code: "KG", country: "Kyrgyzstan", dialCode: "+996" },
  { code: "LA", country: "Laos", dialCode: "+856" },
  { code: "LV", country: "Latvia", dialCode: "+371" },
  { code: "LB", country: "Lebanon", dialCode: "+961" },
  { code: "LS", country: "Lesotho", dialCode: "+266" },
  { code: "LR", country: "Liberia", dialCode: "+231" },
  { code: "LY", country: "Libya", dialCode: "+218" },
  { code: "LI", country: "Liechtenstein", dialCode: "+423" },
  { code: "LT", country: "Lithuania", dialCode: "+370" },
  { code: "LU", country: "Luxembourg", dialCode: "+352" },
  { code: "MG", country: "Madagascar", dialCode: "+261" },
  { code: "MW", country: "Malawi", dialCode: "+265" },
  { code: "MY", country: "Malaysia", dialCode: "+60" },
  { code: "MV", country: "Maldives", dialCode: "+960" },
  { code: "ML", country: "Mali", dialCode: "+223" },
  { code: "MT", country: "Malta", dialCode: "+356" },
  { code: "MR", country: "Mauritania", dialCode: "+222" },
  { code: "MU", country: "Mauritius", dialCode: "+230" },
  { code: "MX", country: "Mexico", dialCode: "+52" },
  { code: "MD", country: "Moldova", dialCode: "+373" },
  { code: "MC", country: "Monaco", dialCode: "+377" },
  { code: "MN", country: "Mongolia", dialCode: "+976" },
  { code: "ME", country: "Montenegro", dialCode: "+382" },
  { code: "MA", country: "Morocco", dialCode: "+212" },
  { code: "MZ", country: "Mozambique", dialCode: "+258" },
  { code: "MM", country: "Myanmar", dialCode: "+95" },
  { code: "NA", country: "Namibia", dialCode: "+264" },
  { code: "NP", country: "Nepal", dialCode: "+977" },
  { code: "NL", country: "Netherlands", dialCode: "+31" },
  { code: "NZ", country: "New Zealand", dialCode: "+64" },
  { code: "NI", country: "Nicaragua", dialCode: "+505" },
  { code: "NE", country: "Niger", dialCode: "+227" },
  { code: "NG", country: "Nigeria", dialCode: "+234" },
  { code: "KP", country: "North Korea", dialCode: "+850" },
  { code: "MK", country: "North Macedonia", dialCode: "+389" },
  { code: "NO", country: "Norway", dialCode: "+47" },
  { code: "OM", country: "Oman", dialCode: "+968" },
  { code: "PK", country: "Pakistan", dialCode: "+92" },
  { code: "PS", country: "Palestine", dialCode: "+970" },
  { code: "PA", country: "Panama", dialCode: "+507" },
  { code: "PG", country: "Papua New Guinea", dialCode: "+675" },
  { code: "PY", country: "Paraguay", dialCode: "+595" },
  { code: "PE", country: "Peru", dialCode: "+51" },
  { code: "PH", country: "Philippines", dialCode: "+63" },
  { code: "PL", country: "Poland", dialCode: "+48" },
  { code: "PT", country: "Portugal", dialCode: "+351" },
  { code: "QA", country: "Qatar", dialCode: "+974" },
  { code: "RO", country: "Romania", dialCode: "+40" },
  { code: "RU", country: "Russia", dialCode: "+7" },
  { code: "RW", country: "Rwanda", dialCode: "+250" },
  { code: "SA", country: "Saudi Arabia", dialCode: "+966" },
  { code: "SN", country: "Senegal", dialCode: "+221" },
  { code: "RS", country: "Serbia", dialCode: "+381" },
  { code: "SC", country: "Seychelles", dialCode: "+248" },
  { code: "SL", country: "Sierra Leone", dialCode: "+232" },
  { code: "SG", country: "Singapore", dialCode: "+65" },
  { code: "SK", country: "Slovakia", dialCode: "+421" },
  { code: "SI", country: "Slovenia", dialCode: "+386" },
  { code: "SO", country: "Somalia", dialCode: "+252" },
  { code: "KR", country: "South Korea", dialCode: "+82" },
  { code: "SS", country: "South Sudan", dialCode: "+211" },
  { code: "ES", country: "Spain", dialCode: "+34" },
  { code: "LK", country: "Sri Lanka", dialCode: "+94" },
  { code: "SD", country: "Sudan", dialCode: "+249" },
  { code: "SR", country: "Suriname", dialCode: "+597" },
  { code: "SE", country: "Sweden", dialCode: "+46" },
  { code: "CH", country: "Switzerland", dialCode: "+41" },
  { code: "SY", country: "Syria", dialCode: "+963" },
  { code: "TW", country: "Taiwan", dialCode: "+886" },
  { code: "TJ", country: "Tajikistan", dialCode: "+992" },
  { code: "TZ", country: "Tanzania", dialCode: "+255" },
  { code: "TH", country: "Thailand", dialCode: "+66" },
  { code: "TL", country: "Timor-Leste", dialCode: "+670" },
  { code: "TG", country: "Togo", dialCode: "+228" },
  { code: "TO", country: "Tonga", dialCode: "+676" },
  { code: "TT", country: "Trinidad and Tobago", dialCode: "+1-868" },
  { code: "TN", country: "Tunisia", dialCode: "+216" },
  { code: "TR", country: "Turkey", dialCode: "+90" },
  { code: "TM", country: "Turkmenistan", dialCode: "+993" },
  { code: "UG", country: "Uganda", dialCode: "+256" },
  { code: "UA", country: "Ukraine", dialCode: "+380" },
  { code: "AE", country: "United Arab Emirates", dialCode: "+971" },
  { code: "GB", country: "United Kingdom", dialCode: "+44" },
  { code: "US", country: "United States", dialCode: "+1" },
  { code: "UY", country: "Uruguay", dialCode: "+598" },
  { code: "UZ", country: "Uzbekistan", dialCode: "+998" },
  { code: "VU", country: "Vanuatu", dialCode: "+678" },
  { code: "VA", country: "Vatican City", dialCode: "+379" },
  { code: "VE", country: "Venezuela", dialCode: "+58" },
  { code: "VN", country: "Vietnam", dialCode: "+84" },
  { code: "YE", country: "Yemen", dialCode: "+967" },
  { code: "ZM", country: "Zambia", dialCode: "+260" },
  { code: "ZW", country: "Zimbabwe", dialCode: "+263" },
];

export const DEFAULT_COUNTRY_CODE = "+27";
