/**
 * Centralized list of South African job titles organized by industry.
 * Used throughout the application for:
 * - Individual job seeker profiles
 * - Recruiter job postings
 * - Business job postings
 * - ATS candidate screening
 */

export interface JobTitleCategory {
  industry: string;
  titles: string[];
}

export const JOB_TITLES_BY_INDUSTRY: JobTitleCategory[] = [
  {
    industry: "Accounting, Finance & Auditing",
    titles: [
      "Accountant",
      "Accountant (Government)",
      "Accounts Assistant",
      "Accounts Clerk",
      "Accounts Manager",
      "Accounts Payable Clerk",
      "Accounts Receivable Clerk",
      "Auditor",
      "Bookkeeper",
      "Budget Analyst",
      "Cost Accountant",
      "Costing Clerk",
      "Credit Controller",
      "Debtors Clerk",
      "Finance Administrator",
      "Finance Manager",
      "Financial Analyst",
      "Financial Controller",
      "Payroll Administrator",
      "Payroll Clerk",
      "Treasury Analyst",
      "Tax Consultant",
      "VAT Specialist",
    ],
  },
  {
    industry: "Administration, Office & Support",
    titles: [
      "Admin Assistant",
      "Admin Clerk",
      "Administrator",
      "Administrative Clerk",
      "Administrative Officer",
      "Assistant Director",
      "Chief Director",
      "Clerk",
      "Executive Assistant",
      "Office Administrator",
      "Office Assistant",
      "Personal Assistant",
      "Receptionist",
      "Secretary",
      "Senior Clerk",
      "Typist",
      "Data Capturer (Government)",
      "Messenger",
    ],
  },
  {
    industry: "Information Technology & Digital",
    titles: [
      "Application Developer",
      "Computer Technician",
      "Data Analyst",
      "Data Engineer",
      "Data Scientist",
      "Database Administrator",
      "Front-End Developer",
      "Full Stack Developer",
      "IT Administrator",
      "IT Consultant",
      "IT Coordinator",
      "IT Manager",
      "IT Support Technician",
      "Network Administrator",
      "Network Engineer",
      "Software Developer",
      "Software Engineer",
      "Software Tester",
      "Solution Architect",
      "Systems Administrator",
      "Systems Analyst",
      "Web Developer",
      "Web Designer",
      "Webmaster",
    ],
  },
  {
    industry: "Engineering, Technical & Construction",
    titles: [
      "Architect",
      "Artisan (Plumber)",
      "Artisan (Electrician)",
      "Artisan (Carpenter)",
      "Auto Electrician",
      "Automotive Mechanic",
      "Building Inspector",
      "Civil Engineer",
      "Civil Engineer (Government)",
      "Construction Manager",
      "Electrical Engineer",
      "Electrical Engineer (Government)",
      "Engineer",
      "Maintenance Manager",
      "Mechanical Engineer",
      "Mining Engineer",
      "Project Engineer",
      "Quantity Surveyor",
      "Quantity Surveyor (Government)",
      "Site Manager",
      "Town Planner",
    ],
  },
  {
    industry: "Manufacturing, Production & Skilled Trades",
    titles: [
      "Assembler",
      "CNC Operator",
      "Diesel Mechanic",
      "Fitter",
      "Machinist",
      "Maintenance Assistant",
      "Plant Operator",
      "Production Manager",
      "Quality Assurance Manager",
      "Quality Control Inspector",
      "Technician",
      "Toolmaker",
      "Welder",
      "Workshop Foreman",
    ],
  },
  {
    industry: "Business, Consulting & Strategy",
    titles: [
      "Analyst",
      "Associate Consultant",
      "Business Analyst",
      "Business Consultant",
      "Business Development Executive",
      "Business Development Manager",
      "Business Manager",
      "Consultant",
      "Management Consultant",
      "Operations Manager",
      "Project Manager",
      "Strategic Planner",
    ],
  },
  {
    industry: "Sales, Marketing & Communications",
    titles: [
      "Advertising Executive",
      "Brand Manager",
      "Communications Officer",
      "Content Creator",
      "Copywriter",
      "Customer Service Agent",
      "Customer Service Manager",
      "Digital Marketing Manager",
      "Marketing Assistant",
      "Marketing Coordinator",
      "Marketing Executive",
      "Marketing Manager",
      "Product Manager",
      "Public Relations Officer",
      "Sales Assistant",
      "Sales Consultant",
      "Sales Executive",
      "Sales Manager",
      "Sales Representative",
      "Social Media Manager",
    ],
  },
  {
    industry: "Human Resources & Recruitment",
    titles: [
      "HR Administrator",
      "HR Assistant",
      "HR Consultant",
      "HR Coordinator",
      "HR Manager",
      "Human Resources Officer",
      "Labour Relations Officer",
      "Recruiter",
      "Training Coordinator",
      "Training Facilitator",
    ],
  },
  {
    industry: "Healthcare & Medical",
    titles: [
      "Auxiliary Nurse",
      "Clinical Associate",
      "Clinical Psychologist",
      "Dental Assistant",
      "Dental Therapist",
      "Dentist",
      "Dietitian",
      "Doctor",
      "Healthcare Assistant",
      "Medical Administrator",
      "Medical Officer",
      "Medical Receptionist",
      "Medical Representative",
      "Nurse",
      "Nutritionist",
      "Occupational Therapist",
      "Paramedic",
      "Pharmacist",
      "Pharmacy Assistant",
      "Physical Therapist",
      "Physiotherapist",
    ],
  },
  {
    industry: "Education & Training",
    titles: [
      "Chief Education Specialist",
      "Curriculum Advisor",
      "Early Childhood Educator",
      "Education Development Officer",
      "Education Specialist",
      "Educator (Primary)",
      "Educator (Secondary)",
      "Examination Officer",
      "Head of Department (HOD)",
      "Lecturer",
      "Principal",
      "School Administrator",
      "School Teacher",
      "Teacher",
      "Teaching Assistant",
      "Trainer",
      "Tutor",
    ],
  },
  {
    industry: "Legal & Compliance",
    titles: [
      "Attorney",
      "Compliance Officer",
      "Court Interpreter",
      "Court Messenger",
      "Court Orderly",
      "Court Registrar",
      "Judge's Secretary",
      "Lawyer",
      "Legal Advisor",
      "Legal Assistant",
      "Legal Clerk",
      "Legal Officer",
      "Paralegal",
      "Prosecutor",
      "State Attorney",
    ],
  },
  {
    industry: "Logistics, Transport & Supply Chain",
    titles: [
      "Delivery Driver",
      "Dispatch Clerk",
      "Distribution Manager",
      "Driver",
      "Fleet Manager",
      "Forklift Operator",
      "Logistics Administrator",
      "Logistics Assistant",
      "Logistics Coordinator",
      "Logistics Manager",
      "Supply Chain Analyst",
      "Supply Chain Clerk",
      "Supply Chain Manager",
      "Supply Chain Specialist",
      "Transport Manager",
      "Truck Driver",
      "Warehouse Assistant",
      "Warehouse Manager",
    ],
  },
  {
    industry: "Government & Public Service",
    titles: [
      "Actuary",
      "Chief Financial Officer (Government)",
      "Chief Policy Analyst",
      "Complaints Investigator",
      "Deputy Director",
      "Deputy Director: Finance",
      "Director",
      "Director-General",
      "Environmental Health Officer",
      "Environmental Health Practitioner",
      "Extension Officer",
      "Information Officer",
      "Policy Analyst",
      "Policy Researcher",
      "Procurement Officer",
      "Procurement Specialist",
      "Public Administration Officer",
      "Revenue Officer",
      "Roads Superintendent",
      "Rural Development Coordinator",
    ],
  },
  {
    industry: "Hospitality, Tourism & Events",
    titles: [
      "Baker",
      "Barista",
      "Bartender",
      "Chef",
      "Cook",
      "Event Coordinator",
      "Event Manager",
      "Executive Chef",
      "Front Desk Assistant",
      "Front Desk Manager",
      "Head Chef",
      "Restaurant Manager",
      "Tour Guide",
      "Waiter",
    ],
  },
  {
    industry: "Security, Defence & Law Enforcement",
    titles: [
      "Correctional Officer",
      "Detective",
      "Forensic Analyst",
      "Immigration Officer",
      "Police Constable",
      "Police Sergeant",
      "Prison Warder",
      "Security Guard",
      "Security Officer",
      "Traffic Officer",
    ],
  },
  {
    industry: "Art, Design & Media",
    titles: [
      "Animator",
      "Art Director",
      "Designer",
      "Fashion Designer",
      "Graphic Designer",
      "Industrial Designer",
      "Interior Designer",
      "Photographer",
      "Video Editor",
    ],
  },
  {
    industry: "Science & Research",
    titles: [
      "Biologist",
      "Chemist",
      "Environmental Scientist",
      "Geologist",
      "Laboratory Assistant",
      "Laboratory Technician",
      "Marine Biologist",
      "Research Analyst",
      "Research Assistant",
      "Scientist",
    ],
  },
  {
    industry: "Agriculture & Environment",
    titles: [
      "Agricultural Advisor",
      "Agricultural Consultant",
      "Agricultural Engineer",
      "Agricultural Labourer",
      "Agronomist",
      "Animal Health Technician",
      "Conservation Officer",
      "Environmental Consultant",
      "Environmental Manager",
      "Forestry Technician",
      "Nature Reserve Manager",
    ],
  },
  {
    industry: "Retail, Wholesale & Customer Service",
    titles: [
      "Buyer",
      "Cashier",
      "Customer Care Agent",
      "Customer Relations Officer",
      "Merchandiser",
      "Retail Assistant",
      "Retail Manager",
      "Service Advisor",
      "Store Assistant",
      "Store Manager",
    ],
  },
  {
    industry: "Property & Facilities Management",
    titles: [
      "Facilities Manager",
      "Property Manager",
      "Landscape Architect",
    ],
  },
  {
    industry: "Trades, General Labour & Maintenance",
    titles: [
      "Beautician",
      "Carpenter",
      "Cleaner",
      "Electrician",
      "General Labourer",
      "Hair Stylist",
      "Handyman",
      "Machine Operator",
      "Maintenance Foreman",
      "Makeup Artist",
      "Mason",
      "Mechanic",
      "Painter",
      "Plumber",
      "Power Plant Operator",
      "Tailor",
    ],
  },
  {
    industry: "Media, Publishing & Journalism",
    titles: [
      "Editor",
      "Journalist",
      "Sound Engineer",
    ],
  },
  {
    industry: "Other Specialized Roles",
    titles: [
      "Appraiser",
      "Broker",
      "Call Centre Agent",
      "Call Centre Manager",
      "Client Relationship Manager",
      "Client Services Manager",
      "Community Development Worker",
      "Community Health Worker",
      "Contract Manager",
      "Controller",
      "Counsellor",
      "Debt Collector",
      "Ecommerce Manager",
      "Estimator",
      "Fund Accountant",
      "GIS Specialist",
      "General Manager",
      "Helpdesk Agent",
      "Insurance Broker",
      "Insurance Consultant",
      "Intern",
      "Internal Auditor",
      "Investment Analyst",
      "Librarian",
      "Life Coach",
      "Portfolio Manager",
      "Post Office Clerk",
      "Procurement Manager",
      "Product Designer",
      "Programme Coordinator",
      "Programmer",
      "Project Administrator",
      "Project Coordinator",
      "Project Officer",
      "Quality Assurance Analyst",
      "Quality Assurance Inspector",
      "Regional Manager",
      "Relationship Manager",
      "Safety Officer",
      "Sales Administrator",
      "Scrum Master",
      "Senior Accountant",
      "Senior Analyst",
      "Senior Developer",
      "Senior Engineer",
      "Senior Manager",
      "Senior Project Manager",
      "Social Worker",
      "Student Intern",
      "Supervisor",
      "Support Engineer",
      "Technical Assistant",
      "Technical Consultant",
      "Technical Support Engineer",
      "Telemarketer",
      "UX Designer",
    ],
  },
];

// Flatten all job titles into a single array for backward compatibility
export const JOB_TITLES = [
  ...JOB_TITLES_BY_INDUSTRY.flatMap((category) => category.titles),
  "Other",
] as const;

export type JobTitle = typeof JOB_TITLES[number];

/**
 * Helper function to get the industry for a given job title
 */
export function getIndustryForJobTitle(jobTitle: string): string {
  for (const category of JOB_TITLES_BY_INDUSTRY) {
    if (category.titles.includes(jobTitle)) {
      return category.industry;
    }
  }
  return "Other"; // Default for "Other" or unknown titles
}
